# Generated by Django 4.2.7 on 2023-11-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_contato_options_contato_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='complemento',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo'), ('MG', 'Minas Gerais')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
