# Generated by Django 4.2.7 on 2023-11-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0003_alter_contato_complemento_alter_contato_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='cidade',
        ),
    ]
