# Generated by Django 4.2.7 on 2023-11-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0004_remove_contato_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='cidade',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
